### ISSUE TITLE
Force inserts GlblRes using statements

### ISSUE THREAD

**Issue by isaksavo** [Dany-R/IBR.StringResourceBuilder2011#3]
I set the extension to use the global resource file (under Resources.resx under Properties)

When I convert a literal to resource, the tool adds a `GlblRes` using statement pointing to Properties.Resources

I assume it's done like this for a reason (why?), but it would be nice be able to turn that feature off and simply have it say `Properties.Resources.TheNameOfTheResourceString`

**Comment by Dany-R** [comment]
Hi Isak,
it has been this way, because I'd like to shorten the code to type or read and nobody "complained" until now. 😉
I just updated it with a new sub-option for global resources here and in the VS Marketplace ([V1.6.1.22](https://github.com/Dany-R/IBR.StringResourceBuilder2011/releases/tag/V1.6.1.22)). 
Please give it a try and tell me, if this is what you proposed.
Cheers, Dany
